---
- hosts: all
  become: true
  roles:
    - common
#    - icon-monitoring-configs
    - { role: "dev-sec.os-hardening", when: (ansible_hardening | default(false)) }
    - { role: "dev-sec.ssh-hardening", when: (ansible_hardening | default(false)) }
    - { role: "cloudalchemy.prometheus", when: (prometheus_enabled | default(true))}
    - { role: "cloudalchemy.grafana",  when: (grafana_enabled | default(true))}
    - { role: "cloudalchemy.alertmanager",  when: (alertmanager_enabled | default(true))}
    - { role: sachet, when: (alertmanager_enabled | default(false)) }
